# Generated by Django 5.1.1 on 2025-01-30 23:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('location', '0001_initial'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerlocation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_location', to='userauth.customer'),
        ),
        migrations.AddField(
            model_name='serviceproviderlocation',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='serviceprovider_location', to='userauth.serviceprovider'),
        ),
    ]
