# Generated by Django 5.1.1 on 2025-12-20 20:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('location', '0002_initial'),
        ('userauth', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerlocation',
            name='customer',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_location', to='userauth.customer'),
        ),
        migrations.AlterField(
            model_name='serviceproviderlocation',
            name='service_provider',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='serviceprovider_location', to='userauth.serviceprovider'),
        ),
    ]
