# Generated by Django 5.1.1 on 2025-01-31 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycverification', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='selected_services',
        ),
        migrations.RemoveField(
            model_name='kyc',
            name='working_type',
        ),
        migrations.AddField(
            model_name='kyc',
            name='work_type',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.DeleteModel(
            name='Service',
        ),
    ]
