# Generated by Django 5.1.1 on 2025-01-31 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycverification', '0003_remove_kyc_selected_services_remove_kyc_working_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='kyc',
            name='work_type',
        ),
        migrations.AddField(
            model_name='kyc',
            name='woork_type',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
