# Generated by Django 5.1.1 on 2025-01-31 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kycverification', '0004_remove_kyc_work_type_kyc_woork_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kyc',
            name='woork_type',
            field=models.TextField(default=''),
            preserve_default=False,
        ),
    ]
