# Generated by Django 5.1.1 on 2025-01-30 23:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ratings', '0001_initial'),
        ('userauth', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.customer'),
        ),
        migrations.AddField(
            model_name='booking',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.serviceprovider'),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.booking'),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.customer'),
        ),
        migrations.AddField(
            model_name='cancellation',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.serviceprovider'),
        ),
        migrations.AddField(
            model_name='rating',
            name='booking',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ratings.booking'),
        ),
        migrations.AddField(
            model_name='rating',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.customer'),
        ),
        migrations.AddField(
            model_name='rating',
            name='service_provider',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='userauth.serviceprovider'),
        ),
        migrations.AddField(
            model_name='serviceprovideravgrating',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
