# Generated by Django 5.1.1 on 2026-01-17 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ratings', '0005_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='notification',
            name='recipient_role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='notification',
            name='sender_role',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
